/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => HandnotesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/HandnotesView.ts
var import_obsidian3 = require("obsidian");

// src/canvas/PressureCurve.ts
function monotoneCubicSpline(controlPoints) {
  const n = controlPoints.length;
  if (n < 2)
    return (t) => t;
  const xs = controlPoints.map((p) => p.x);
  const ys = controlPoints.map((p) => p.y);
  const dx = [];
  const dy = [];
  const slopes = [];
  for (let i = 0; i < n - 1; i++) {
    dx[i] = xs[i + 1] - xs[i];
    dy[i] = ys[i + 1] - ys[i];
    if (dx[i] === 0) {
      slopes[i] = 0;
    } else {
      slopes[i] = dy[i] / dx[i];
    }
  }
  const tangents = new Array(n);
  if (n === 2) {
    tangents[0] = slopes[0];
    tangents[1] = slopes[0];
  } else {
    tangents[0] = slopes[0];
    tangents[n - 1] = slopes[n - 2];
    for (let i = 1; i < n - 1; i++) {
      if (slopes[i - 1] * slopes[i] <= 0) {
        tangents[i] = 0;
      } else {
        tangents[i] = (dx[i - 1] + dx[i]) / (dx[i - 1] / slopes[i - 1] + dx[i] / slopes[i]);
      }
    }
  }
  for (let i = 0; i < n - 1; i++) {
    const a = tangents[i] / slopes[i];
    const b = tangents[i + 1] / slopes[i];
    if (a * a + b * b > 9) {
      const t = 3 / Math.sqrt(a * a + b * b);
      tangents[i] = t * a * slopes[i];
      tangents[i + 1] = t * b * slopes[i];
    }
  }
  return function(t) {
    if (t <= xs[0])
      return ys[0];
    if (t >= xs[n - 1])
      return ys[n - 1];
    let i = 0;
    for (let j = 0; j < n - 1; j++) {
      if (t >= xs[j] && t < xs[j + 1]) {
        i = j;
        break;
      }
    }
    const h = dx[i];
    if (h === 0)
      return ys[i];
    const s = (t - xs[i]) / h;
    const s2 = s * s;
    const s3 = s2 * s;
    const h00 = 2 * s3 - 3 * s2 + 1;
    const h10 = s3 - 2 * s2 + s;
    const h01 = -2 * s3 + 3 * s2;
    const h11 = s3 - s2;
    return h00 * ys[i] + h10 * tangents[i] * h + h01 * ys[i + 1] + h11 * tangents[i + 1] * h;
  };
}
function applyPressureCurve(rawPressure, curve) {
  if (!curve || !curve.points || curve.points.length < 2) {
    return Math.max(0, Math.min(1, rawPressure));
  }
  try {
    const interpolator = monotoneCubicSpline(curve.points);
    const result = interpolator(Math.max(0, Math.min(1, rawPressure)));
    if (curve.clamp) {
      return Math.max(0, Math.min(1, result));
    }
    return result;
  } catch {
    return Math.max(0, Math.min(1, rawPressure));
  }
}

// src/canvas/Smoothing.ts
function smoothPoints(points, amount) {
  if (amount <= 0 || points.length < 3)
    return points;
  const windowSize = Math.max(2, Math.min(10, 1 + Math.floor(amount / 20)));
  const result = [];
  for (let i = 0; i < points.length; i++) {
    const start = Math.max(0, i - windowSize + 1);
    const end = i + 1;
    let wx = 0, wy = 0, wp = 0, wt = 0;
    let totalWeight = 0;
    for (let j = start; j < end; j++) {
      const w = 1 + (j - start);
      wx += points[j].x * w;
      wy += points[j].y * w;
      wp += points[j].pressure * w;
      wt += points[j].t * w;
      totalWeight += w;
    }
    result.push({
      x: wx / totalWeight,
      y: wy / totalWeight,
      pressure: wp / totalWeight,
      t: wt / totalWeight
    });
  }
  return result;
}

// src/tools/Tools.ts
function getStrokeWidth(tool, baseWidth, pressure, pressureEnabled) {
  if (!pressureEnabled)
    return baseWidth;
  switch (tool) {
    case "fountain":
      return baseWidth * (0.3 + 0.7 * pressure);
    case "ballpoint":
      return baseWidth * (0.6 + 0.4 * pressure);
    case "pencil":
      return baseWidth * (0.4 + 0.6 * pressure);
    case "marker":
      return baseWidth;
    case "eraser":
      return baseWidth * (0.5 + 0.5 * pressure);
    default:
      return baseWidth;
  }
}
function getStrokeOpacity(tool, baseOpacity) {
  switch (tool) {
    case "marker":
      return Math.min(baseOpacity, 0.5);
    default:
      return baseOpacity;
  }
}
function buildStrokePath(rawPoints, smoothingWindow) {
  if (smoothingWindow <= 1 || rawPoints.length < 3) {
    return rawPoints.slice();
  }
  return smoothPoints(rawPoints, (smoothingWindow - 1) * 20);
}
function renderStroke(ctx, stroke, pressureEnabled, noisePattern) {
  const pts = stroke.points;
  if (pts.length < 2) {
    if (pts.length === 1) {
      renderDot(ctx, stroke, pts[0], pressureEnabled, noisePattern);
    }
    return;
  }
  ctx.save();
  const opacity = getStrokeOpacity(stroke.tool, stroke.opacity);
  ctx.globalAlpha = opacity;
  const isPencil = stroke.tool === "pencil" && noisePattern;
  if (isPencil) {
    const pattern = ctx.createPattern(noisePattern, "repeat");
    if (pattern) {
      ctx.strokeStyle = pattern;
      ctx.fillStyle = pattern;
    } else {
      ctx.strokeStyle = stroke.color;
      ctx.fillStyle = stroke.color;
    }
    ctx.globalCompositeOperation = "multiply";
  } else {
    ctx.strokeStyle = stroke.color;
    ctx.fillStyle = stroke.color;
  }
  ctx.lineCap = "round";
  ctx.lineJoin = "round";
  for (let i = 0; i < pts.length - 1; i++) {
    const p0 = pts[i];
    const p1 = pts[i + 1];
    const w0 = getStrokeWidth(stroke.tool, stroke.width, p0.pressure, pressureEnabled);
    const w1 = getStrokeWidth(stroke.tool, stroke.width, p1.pressure, pressureEnabled);
    if (isPencil || Math.abs(w0 - w1) < 0.1) {
      ctx.lineWidth = w0;
      ctx.beginPath();
      ctx.moveTo(p0.x, p0.y);
      ctx.lineTo(p1.x, p1.y);
      ctx.stroke();
    } else {
      renderTaperedSegment(ctx, p0, p1, w0, w1, stroke.color, opacity);
    }
  }
  if (isPencil) {
    ctx.globalCompositeOperation = "source-over";
  }
  ctx.restore();
}
function renderDot(ctx, stroke, pt, pressureEnabled, noisePattern) {
  const w = getStrokeWidth(stroke.tool, stroke.width, pt.pressure, pressureEnabled);
  ctx.save();
  ctx.globalAlpha = getStrokeOpacity(stroke.tool, stroke.opacity);
  const isPencil = stroke.tool === "pencil" && noisePattern;
  if (isPencil) {
    const pattern = ctx.createPattern(noisePattern, "repeat");
    ctx.fillStyle = pattern || stroke.color;
    ctx.globalCompositeOperation = "multiply";
  } else {
    ctx.fillStyle = stroke.color;
  }
  ctx.beginPath();
  ctx.arc(pt.x, pt.y, w / 2, 0, Math.PI * 2);
  ctx.fill();
  if (isPencil)
    ctx.globalCompositeOperation = "source-over";
  ctx.restore();
}
function renderTaperedSegment(ctx, p0, p1, w0, w1, color, opacity) {
  const dx = p1.x - p0.x;
  const dy = p1.y - p0.y;
  const len = Math.sqrt(dx * dx + dy * dy);
  if (len < 0.5) {
    ctx.lineWidth = (w0 + w1) / 2;
    ctx.beginPath();
    ctx.moveTo(p0.x, p0.y);
    ctx.lineTo(p1.x, p1.y);
    ctx.stroke();
    return;
  }
  const nx = -dy / len;
  const ny = dx / len;
  const hw0 = w0 / 2;
  const hw1 = w1 / 2;
  ctx.fillStyle = color;
  ctx.globalAlpha = opacity;
  ctx.beginPath();
  ctx.moveTo(p0.x + nx * hw0, p0.y + ny * hw0);
  ctx.lineTo(p1.x + nx * hw1, p1.y + ny * hw1);
  ctx.lineTo(p1.x - nx * hw1, p1.y - ny * hw1);
  ctx.lineTo(p0.x - nx * hw0, p0.y - ny * hw0);
  ctx.closePath();
  ctx.fill();
}

// src/canvas/Canvas.ts
var HandwritingCanvas = class {
  constructor(container) {
    this.strokes = [];
    this.undoStack = [];
    this.redoStack = [];
    this.maxUndo = 50;
    this.activeTool = "fountain";
    this.currentColor = "#000000";
    this.currentWidth = 2;
    this.currentOpacity = 1;
    this.toolPressureEnabled = {};
    this.smoothing = 50;
    this.palmRejection = true;
    this.pressureCurve = {
      points: [{ x: 0, y: 0 }, { x: 0.3, y: 0.2 }, { x: 0.7, y: 0.8 }, { x: 1, y: 1 }],
      clamp: true
    };
    this.zoom = 1;
    this.offsetX = 0;
    this.offsetY = 0;
    this.background = "blank";
    this.darkMode = false;
    this.isDrawing = false;
    this.isPanning = false;
    this.rawPoints = [];
    this.lastPointerPos = null;
    this.rafPending = false;
    this.lastDrawnSegment = 0;
    this.needsFullRedraw = true;
    this.selectionPolygon = [];
    this.selectedStrokeIds = /* @__PURE__ */ new Set();
    this.isSelecting = false;
    this.assets = [];
    this.loadedImages = /* @__PURE__ */ new Map();
    this.noisePattern = null;
    this.onSaveNeeded = null;
    this.onStrokeAdded = null;
    this.dpr = 1;
    this._destroyed = false;
    this.container = container;
    this.canvas = document.createElement("canvas");
    this.canvas.style.display = "block";
    this.canvas.style.width = "100%";
    this.canvas.style.height = "100%";
    this.canvas.style.touchAction = "none";
    container.appendChild(this.canvas);
    this.ctx = this.canvas.getContext("2d");
    this.committedCanvas = document.createElement("canvas");
    this.committedCtx = this.committedCanvas.getContext("2d");
    this.dpr = window.devicePixelRatio || 1;
    this.boundPointerDown = this.onPointerDown.bind(this);
    this.boundPointerMove = this.onPointerMove.bind(this);
    this.boundPointerUp = this.onPointerUp.bind(this);
    this.boundKeyDown = this.onKeyDown.bind(this);
    this.boundResize = this.onResize.bind(this);
    this.initNoisePattern();
    this.setupEvents();
    this.ensureCanvasSize();
  }
  setupEvents() {
    this.canvas.addEventListener("pointerdown", this.boundPointerDown);
    this.canvas.addEventListener("pointermove", this.boundPointerMove);
    this.canvas.addEventListener("pointerup", this.boundPointerUp);
    this.canvas.addEventListener("pointerleave", this.boundPointerUp);
    window.addEventListener("keydown", this.boundKeyDown);
    window.addEventListener("resize", this.boundResize);
  }
  onResize() {
    this.ensureCanvasSize();
    this.scheduleRender();
  }
  destroy() {
    this._destroyed = true;
    this.canvas.removeEventListener("pointerdown", this.boundPointerDown);
    this.canvas.removeEventListener("pointermove", this.boundPointerMove);
    this.canvas.removeEventListener("pointerup", this.boundPointerUp);
    this.canvas.removeEventListener("pointerleave", this.boundPointerUp);
    window.removeEventListener("keydown", this.boundKeyDown);
    window.removeEventListener("resize", this.boundResize);
  }
  getCssSize() {
    const rect = this.container.getBoundingClientRect();
    return { w: rect.width, h: rect.height };
  }
  ensureCanvasSize() {
    const { w, h } = this.getCssSize();
    const pw = Math.round(w * this.dpr);
    const ph = Math.round(h * this.dpr);
    if (this.canvas.width !== pw || this.canvas.height !== ph) {
      this.canvas.width = pw;
      this.canvas.height = ph;
    }
    if (this.committedCanvas.width !== pw || this.committedCanvas.height !== ph) {
      this.rebuildCommittedCanvas();
    }
  }
  canvasX(e) {
    const rect = this.canvas.getBoundingClientRect();
    return (e.clientX - rect.left - this.offsetX) / this.zoom;
  }
  canvasY(e) {
    const rect = this.canvas.getBoundingClientRect();
    return (e.clientY - rect.top - this.offsetY) / this.zoom;
  }
  isPenEvent(e) {
    if (!this.palmRejection)
      return true;
    return e.pointerType === "pen" || e.pointerType === "mouse" || e.pointerType === "touch";
  }
  makePoint(e) {
    return {
      x: this.canvasX(e),
      y: this.canvasY(e),
      pressure: applyPressureCurve(e.pressure || 0.5, this.pressureCurve),
      tiltX: e.tiltX || 0,
      tiltY: e.tiltY || 0,
      t: Date.now()
    };
  }
  smoothingWindow() {
    return 1 + Math.floor(this.smoothing / 100 * 2);
  }
  computeAngleChange(p0, p1, p2) {
    const dx1 = p1.x - p0.x;
    const dy1 = p1.y - p0.y;
    const len1 = Math.sqrt(dx1 * dx1 + dy1 * dy1);
    if (len1 < 0.5)
      return 0;
    const dx2 = p2.x - p1.x;
    const dy2 = p2.y - p1.y;
    const len2 = Math.sqrt(dx2 * dx2 + dy2 * dy2);
    if (len2 < 0.5)
      return 0;
    const dot = (dx1 * dx2 + dy1 * dy2) / (len1 * len2);
    return Math.acos(Math.max(-1, Math.min(1, dot)));
  }
  onPointerDown(e) {
    if (this._destroyed)
      return;
    if (!this.isPenEvent(e))
      return;
    const pt = this.makePoint(e);
    if (this.activeTool === "pan") {
      this.isPanning = true;
      this.lastPointerPos = { x: e.clientX, y: e.clientY };
      return;
    }
    if (this.activeTool === "selection") {
      this.isSelecting = true;
      this.selectionPolygon = [pt];
      return;
    }
    if (this.activeTool === "eraser") {
      this.eraseAt(pt.x, pt.y);
      this.isDrawing = true;
      this.rawPoints = [pt];
      return;
    }
    this.isDrawing = true;
    this.rawPoints = [pt];
    this.lastDrawnSegment = 0;
    this.canvas.setPointerCapture(e.pointerId);
    this.scheduleRender();
  }
  onPointerMove(e) {
    if (this._destroyed)
      return;
    if (!this.isPenEvent(e) && !this.isPanning)
      return;
    if (this.isPanning) {
      const dx = e.clientX - (this.lastPointerPos?.x ?? e.clientX);
      const dy = e.clientY - (this.lastPointerPos?.y ?? e.clientY);
      this.offsetX += dx;
      this.offsetY += dy;
      this.lastPointerPos = { x: e.clientX, y: e.clientY };
      this.rebuildCommittedCanvas();
      this.scheduleRender();
      return;
    }
    const pt = this.makePoint(e);
    if (this.isSelecting) {
      if (this.selectionPolygon.length > 0) {
        const last = this.selectionPolygon[this.selectionPolygon.length - 1];
        const dx = pt.x - last.x;
        const dy = pt.y - last.y;
        if (dx * dx + dy * dy < 4)
          return;
      }
      this.selectionPolygon.push(pt);
      this.scheduleRender();
      return;
    }
    if (!this.isDrawing)
      return;
    if (this.activeTool === "eraser") {
      this.eraseAt(pt.x, pt.y);
      return;
    }
    if (this.rawPoints.length >= 5e3)
      return;
    if (this.rawPoints.length > 0) {
      const last = this.rawPoints[this.rawPoints.length - 1];
      const dx = pt.x - last.x;
      const dy = pt.y - last.y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      if (dist < 0.5)
        return;
      if (this.rawPoints.length >= 2) {
        const prev = this.rawPoints[this.rawPoints.length - 2];
        const angle = this.computeAngleChange(prev, last, pt);
        if (angle > 0.35) {
          this.rawPoints.push(pt);
          this.scheduleRender();
          return;
        }
      }
    }
    this.rawPoints.push(pt);
    this.scheduleRender();
  }
  onPointerUp(e) {
    if (this._destroyed)
      return;
    if (this.isPanning) {
      this.isPanning = false;
      this.lastPointerPos = null;
      return;
    }
    if (this.isSelecting) {
      this.isSelecting = false;
      this.finishSelection();
      return;
    }
    if (!this.isDrawing)
      return;
    this.isDrawing = false;
    if (this.activeTool === "eraser") {
      this.rawPoints = [];
      this.scheduleRender();
      return;
    }
    if (this.rawPoints.length < 1)
      return;
    this.canvas.releasePointerCapture(e.pointerId);
    this.finalizeStroke();
  }
  finalizeStroke() {
    const raw = this.rawPoints;
    this.rawPoints = [];
    const win = this.smoothingWindow();
    const commitPoints = buildStrokePath(raw, win);
    if (commitPoints.length < 1)
      return;
    const frozenPoints = Object.freeze(
      commitPoints.map((p) => Object.freeze({ ...p }))
    );
    const stroke = Object.freeze({
      id: `s_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`,
      tool: this.activeTool,
      color: this.currentColor,
      width: this.currentWidth,
      opacity: this.activeTool === "marker" ? Math.min(this.currentOpacity, 0.5) : this.currentOpacity,
      points: frozenPoints,
      timestamp: Date.now()
    });
    this.undoStack.push(this.strokes);
    if (this.undoStack.length > this.maxUndo)
      this.undoStack.shift();
    this.redoStack = [];
    this.strokes = [...this.strokes, stroke];
    this.renderStrokeOnCtx(this.committedCtx, stroke);
    this.onStrokeAdded?.();
    this.onSaveNeeded?.();
    this.scheduleRender();
  }
  eraseAt(x, y) {
    const threshold = this.currentWidth * 10;
    const before = this.strokes.length;
    const kept = this.strokes.filter((s) => {
      for (const p of s.points) {
        const dx = p.x - x;
        const dy = p.y - y;
        if (dx * dx + dy * dy < threshold * threshold)
          return false;
      }
      return true;
    });
    if (kept.length !== before) {
      this.undoStack.push(this.strokes);
      this.strokes = kept;
      this.rebuildCommittedCanvas();
      this.onSaveNeeded?.();
      this.scheduleRender();
    }
  }
  isPointInPolygon(px, py, polygon) {
    let inside = false;
    const n = polygon.length;
    if (n < 3)
      return false;
    for (let i = 0, j = n - 1; i < n; j = i++) {
      const xi = polygon[i].x, yi = polygon[i].y;
      const xj = polygon[j].x, yj = polygon[j].y;
      if (yi > py !== yj > py && px < (xj - xi) * (py - yi) / (yj - yi) + xi) {
        inside = !inside;
      }
    }
    return inside;
  }
  finishSelection() {
    if (this.selectionPolygon.length < 3) {
      this.selectionPolygon = [];
      this.selectedStrokeIds.clear();
      this.scheduleRender();
      return;
    }
    this.selectedStrokeIds.clear();
    for (const s of this.strokes) {
      let cx = 0, cy = 0, count = 0;
      for (const p of s.points) {
        cx += p.x;
        cy += p.y;
        count++;
      }
      if (count > 0) {
        cx /= count;
        cy /= count;
        if (this.isPointInPolygon(cx, cy, this.selectionPolygon)) {
          this.selectedStrokeIds.add(s.id);
        }
      }
    }
    this.scheduleRender();
  }
  deleteSelected() {
    if (this.selectedStrokeIds.size === 0)
      return;
    this.undoStack.push(this.strokes);
    this.strokes = this.strokes.filter((s) => !this.selectedStrokeIds.has(s.id));
    this.selectedStrokeIds.clear();
    this.rebuildCommittedCanvas();
    this.onSaveNeeded?.();
    this.scheduleRender();
  }
  copySelected() {
    if (this.selectedStrokeIds.size === 0)
      return;
    this.undoStack.push(this.strokes);
    const newStrokes = [];
    for (const s of this.strokes) {
      if (this.selectedStrokeIds.has(s.id)) {
        const copy = JSON.parse(JSON.stringify(s));
        copy.id = `s_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
        for (const p of copy.points) {
          p.x += 20;
          p.y += 20;
        }
        copy.timestamp = Date.now();
        newStrokes.push(copy);
      }
    }
    this.strokes = [...this.strokes, ...newStrokes];
    this.rebuildCommittedCanvas();
    this.onSaveNeeded?.();
    this.scheduleRender();
  }
  clearSelection() {
    this.selectionPolygon = [];
    this.selectedStrokeIds.clear();
    this.scheduleRender();
  }
  onKeyDown(e) {
    if (e.key === "Delete" || e.key === "Backspace") {
      if (this.selectedStrokeIds.size > 0) {
        e.preventDefault();
        this.deleteSelected();
      }
    }
    if (e.key === "Escape") {
      this.clearSelection();
    }
    if ((e.ctrlKey || e.metaKey) && e.key === "z") {
      e.preventDefault();
      if (e.shiftKey)
        this.redo();
      else
        this.undo();
    }
  }
  undo() {
    if (this.undoStack.length === 0)
      return;
    this.redoStack.push(this.strokes);
    this.strokes = this.undoStack.pop();
    this.rebuildCommittedCanvas();
    this.onSaveNeeded?.();
    this.scheduleRender();
  }
  redo() {
    if (this.redoStack.length === 0)
      return;
    this.undoStack.push(this.strokes);
    this.strokes = this.redoStack.pop();
    this.rebuildCommittedCanvas();
    this.onSaveNeeded?.();
    this.scheduleRender();
  }
  setZoom(z) {
    this.zoom = Math.max(0.1, Math.min(10, z));
    this.rebuildCommittedCanvas();
    this.scheduleRender();
  }
  setOffset(x, y) {
    this.offsetX = x;
    this.offsetY = y;
    this.rebuildCommittedCanvas();
    this.scheduleRender();
  }
  setLayout(layout) {
    this.background = layout;
    this.scheduleRender();
  }
  setTool(tool) {
    this.activeTool = tool;
  }
  setColor(color) {
    this.currentColor = color;
  }
  setWidth(width) {
    this.currentWidth = Math.max(0.5, width);
  }
  setOpacity(opacity) {
    this.currentOpacity = Math.max(0, Math.min(1, opacity));
  }
  setSmoothing(amount) {
    this.smoothing = Math.max(0, Math.min(100, amount));
  }
  setPalmRejection(enabled) {
    this.palmRejection = enabled;
  }
  setToolPressureEnabled(tool, enabled) {
    this.toolPressureEnabled[tool] = enabled;
  }
  setPressureCurve(curve) {
    this.pressureCurve = curve;
  }
  setDarkMode(enabled) {
    this.darkMode = enabled;
    this.scheduleRender();
  }
  getBgColor() {
    return this.darkMode ? "#1e1e1e" : "#ffffff";
  }
  getLineColor() {
    return this.darkMode ? "rgba(255,255,255,0.12)" : "rgba(0,0,0,0.10)";
  }
  scheduleRender() {
    if (this.rafPending || this._destroyed)
      return;
    this.rafPending = true;
    requestAnimationFrame(() => {
      this.rafPending = false;
      this.render();
    });
  }
  render() {
    if (this._destroyed)
      return;
    this.ensureCanvasSize();
    const { w, h } = this.getCssSize();
    if (w === 0 || h === 0)
      return;
    const ctx = this.ctx;
    const doFullRedraw = !this.isDrawing || this.needsFullRedraw;
    if (doFullRedraw) {
      ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
      ctx.fillStyle = this.getBgColor();
      ctx.fillRect(0, 0, w, h);
      ctx.save();
      ctx.translate(this.offsetX, this.offsetY);
      ctx.scale(this.zoom, this.zoom);
      this.renderBackground(ctx, w, h);
      this.renderAssets(ctx);
      ctx.drawImage(
        this.committedCanvas,
        0,
        0,
        this.committedCanvas.width,
        this.committedCanvas.height,
        0,
        0,
        w,
        h
      );
      this.renderSelectionOverlay(ctx);
      if (this.activeTool === "selection" && this.isSelecting && this.selectionPolygon.length > 1) {
        this.renderLasso(ctx);
      }
      ctx.restore();
      this.needsFullRedraw = false;
      this.lastDrawnSegment = 0;
    }
    if (this.isDrawing && this.rawPoints.length >= 2) {
      const pts = this.rawPoints;
      const startIdx = Math.max(0, this.lastDrawnSegment);
      if (startIdx < pts.length - 1) {
        const tool = this.activeTool;
        const pressureEnabled = this.toolPressureEnabled[tool] ?? true;
        const opacity = tool === "marker" ? Math.min(this.currentOpacity, 0.5) : this.currentOpacity;
        const isPencil = tool === "pencil" && this.noisePattern !== null;
        ctx.save();
        ctx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
        ctx.translate(this.offsetX, this.offsetY);
        ctx.scale(this.zoom, this.zoom);
        ctx.globalAlpha = opacity;
        if (isPencil) {
          const pattern = ctx.createPattern(this.noisePattern, "repeat");
          ctx.strokeStyle = pattern || this.currentColor;
          ctx.globalCompositeOperation = "multiply";
        } else {
          ctx.strokeStyle = this.currentColor;
        }
        ctx.lineCap = "round";
        ctx.lineJoin = "round";
        for (let i = startIdx; i < pts.length - 1; i++) {
          const p1 = pts[i + 1];
          const w2 = getStrokeWidth(tool, this.currentWidth, p1.pressure, pressureEnabled);
          ctx.lineWidth = w2;
          ctx.beginPath();
          ctx.moveTo(pts[i].x, pts[i].y);
          ctx.lineTo(p1.x, p1.y);
          ctx.stroke();
        }
        if (isPencil)
          ctx.globalCompositeOperation = "source-over";
        ctx.restore();
      }
      this.lastDrawnSegment = pts.length - 1;
    }
  }
  rebuildCommittedCanvas() {
    this.needsFullRedraw = true;
    const { w, h } = this.getCssSize();
    if (w === 0 || h === 0)
      return;
    this.committedCanvas.width = Math.round(w * this.dpr);
    this.committedCanvas.height = Math.round(h * this.dpr);
    this.committedCtx.setTransform(this.dpr, 0, 0, this.dpr, 0, 0);
    for (const stroke of this.strokes) {
      this.renderStrokeOnCtx(this.committedCtx, stroke);
    }
  }
  renderStrokeOnCtx(ctx, stroke) {
    const pressureEnabled = this.toolPressureEnabled[stroke.tool] ?? true;
    const noise = stroke.tool === "pencil" ? this.noisePattern : null;
    renderStroke(ctx, stroke, pressureEnabled, noise);
  }
  renderBackground(ctx, w, h) {
    const lineColor = this.getLineColor();
    ctx.strokeStyle = lineColor;
    ctx.lineWidth = 0.5;
    switch (this.background) {
      case "blank":
        break;
      case "ruled-narrow":
        this.renderRuled(ctx, w, h, 20);
        break;
      case "ruled-wide":
        this.renderRuled(ctx, w, h, 36);
        break;
      case "grid-small":
        this.renderGrid(ctx, w, h, 20);
        break;
      case "grid-large":
        this.renderGrid(ctx, w, h, 40);
        break;
      case "dot":
        this.renderDotGrid(ctx, w, h, 20);
        break;
      case "isometric":
        this.renderIsometric(ctx, w, h, 30);
        break;
    }
  }
  renderRuled(ctx, w, h, spacing) {
    ctx.beginPath();
    for (let y = spacing; y < h; y += spacing) {
      ctx.moveTo(0, y);
      ctx.lineTo(w, y);
    }
    ctx.stroke();
  }
  renderGrid(ctx, w, h, size) {
    ctx.beginPath();
    for (let x = size; x < w; x += size) {
      ctx.moveTo(x, 0);
      ctx.lineTo(x, h);
    }
    for (let y = size; y < h; y += size) {
      ctx.moveTo(0, y);
      ctx.lineTo(w, y);
    }
    ctx.stroke();
  }
  renderDotGrid(ctx, w, h, spacing) {
    ctx.fillStyle = this.getLineColor();
    for (let x = spacing; x < w; x += spacing) {
      for (let y = spacing; y < h; y += spacing) {
        ctx.beginPath();
        ctx.arc(x, y, 1.5, 0, Math.PI * 2);
        ctx.fill();
      }
    }
  }
  renderIsometric(ctx, w, h, size) {
    ctx.beginPath();
    const step = size * Math.sqrt(3) / 2;
    for (let row = -1; row < h / step + 2; row++) {
      const y0 = row * step;
      ctx.moveTo(0, y0);
      ctx.lineTo(w, y0 + w * Math.tan(Math.PI / 6));
      ctx.moveTo(0, y0);
      ctx.lineTo(w, y0 - w * Math.tan(Math.PI / 6));
    }
    for (let x = -w; x < w * 2; x += size * 2) {
      ctx.moveTo(x, 0);
      ctx.lineTo(x + h * Math.tan(Math.PI / 6), h);
    }
    ctx.stroke();
  }
  renderAssets(ctx) {
    for (const asset of this.assets) {
      const img = this.loadedImages.get(asset.path);
      if (img) {
        ctx.drawImage(img, asset.x, asset.y, asset.width, asset.height);
      }
    }
  }
  renderSelectionOverlay(ctx) {
    if (this.selectedStrokeIds.size === 0)
      return;
    ctx.save();
    ctx.strokeStyle = "#3b82f6";
    ctx.lineWidth = 2 / this.zoom;
    ctx.setLineDash([4 / this.zoom, 4 / this.zoom]);
    for (const s of this.strokes) {
      if (!this.selectedStrokeIds.has(s.id))
        continue;
      if (s.points.length === 0)
        continue;
      let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
      for (const p of s.points) {
        if (p.x < minX)
          minX = p.x;
        if (p.y < minY)
          minY = p.y;
        if (p.x > maxX)
          maxX = p.x;
        if (p.y > maxY)
          maxY = p.y;
      }
      const pad = 4 / this.zoom;
      ctx.strokeRect(minX - pad, minY - pad, maxX - minX + pad * 2, maxY - minY + pad * 2);
    }
    ctx.setLineDash([]);
    ctx.restore();
  }
  renderLasso(ctx) {
    if (this.selectionPolygon.length < 2)
      return;
    ctx.save();
    ctx.strokeStyle = "#3b82f6";
    ctx.fillStyle = "rgba(59, 130, 246, 0.08)";
    ctx.lineWidth = 2 / this.zoom;
    ctx.setLineDash([6 / this.zoom, 4 / this.zoom]);
    ctx.beginPath();
    ctx.moveTo(this.selectionPolygon[0].x, this.selectionPolygon[0].y);
    for (let i = 1; i < this.selectionPolygon.length; i++) {
      ctx.lineTo(this.selectionPolygon[i].x, this.selectionPolygon[i].y);
    }
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.setLineDash([]);
    ctx.restore();
  }
  initNoisePattern() {
    const sz = 200;
    const nc = document.createElement("canvas");
    nc.width = sz;
    nc.height = sz;
    const nctx = nc.getContext("2d");
    const imgData = nctx.createImageData(sz, sz);
    for (let i = 0; i < imgData.data.length; i += 4) {
      const v = Math.floor(Math.random() * 80 + 40);
      imgData.data[i] = v;
      imgData.data[i + 1] = v;
      imgData.data[i + 2] = v;
      imgData.data[i + 3] = 60;
    }
    nctx.putImageData(imgData, 0, 0);
    this.noisePattern = nc;
  }
  loadAssets(assets) {
    this.assets = assets;
    for (const a of assets) {
      if (a.type === "image") {
        const img = new Image();
        img.src = a.path;
        img.onload = () => {
          this.loadedImages.set(a.path, img);
          this.scheduleRender();
        };
        img.onerror = () => {
        };
      }
    }
  }
  toHandnotesFile() {
    return {
      version: 1,
      strokes: this.strokes,
      assets: this.assets,
      state: {
        zoom: this.zoom,
        offsetX: this.offsetX,
        offsetY: this.offsetY,
        background: this.background
      }
    };
  }
  fromHandnotesFile(file) {
    this.strokes = file.strokes || [];
    this.assets = file.assets || [];
    if (file.state) {
      this.zoom = file.state.zoom || 1;
      this.offsetX = file.state.offsetX || 0;
      this.offsetY = file.state.offsetY || 0;
      this.background = file.state.background || "blank";
    }
    this.undoStack = [];
    this.redoStack = [];
    this.rebuildCommittedCanvas();
    this.loadAssets(this.assets);
    this.scheduleRender();
  }
  clearAll() {
    this.strokes = [];
    this.undoStack = [];
    this.redoStack = [];
    this.selectedStrokeIds.clear();
    this.selectionPolygon = [];
    this.rebuildCommittedCanvas();
    this.scheduleRender();
  }
};

// src/ui/Toolbar.ts
var import_obsidian = require("obsidian");
var TOOL_SVGS = {
  fountain: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 2l4 4-8 10h-4l-4-4 8-10z"/><path d="M12 16v-4"/><path d="M8 12l-4 4 2 2 4-4"/><path d="M16 12l4 4-2 2-4-4"/></svg>',
  ballpoint: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3l4 4-9 9h-4l-4-4 9-9z"/><path d="M5 16l-2 5 5-2"/><circle cx="19" cy="5" r="1"/></svg>',
  pencil: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 3l4 4-9 9h-4l-4-4 9-9z"/><path d="M5 16l-2 5 5-2"/></svg>',
  marker: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3l6 6-3 3-6-6 3-3z"/><path d="M9 9l-6 6 2 2 6-6"/><path d="M3 15l2 2-2 3 3-2 2 2"/></svg>',
  eraser: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 20H6l-4-4L13 3l7 7-4 4"/><path d="M15.5 5.5l3 3"/><path d="M6 20l4-4"/></svg>',
  selection: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4l16 8-6 2-2 6-8-16z"/><path d="M11 13l5 5"/></svg>',
  pan: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 11V6a2 2 0 00-2-2v0a2 2 0 00-2 2v0"/><path d="M14 10V4a2 2 0 00-2-2v0a2 2 0 00-2 2v2"/><path d="M10 10.5V6a2 2 0 00-2-2v0a2 2 0 00-2 2v8"/><path d="M18 8a2 2 0 114 0v6a8 8 0 01-8 8h-2c-2.21 0-4.21-.9-5.66-2.34L3.5 15.5a1.5 1.5 0 012.12-2.12l2.38 2.38"/></svg>'
};
var Toolbar = class {
  constructor(container, app, callbacks) {
    this.activeTool = "fountain";
    this.currentColor = "#000000";
    this.currentWidth = 2;
    this.currentOpacity = 1;
    this.popupEl = null;
    this.collapsed = false;
    this.recentColors = [
      "#000000",
      "#ff0000",
      "#0000ff",
      "#00aa00",
      "#ff8800",
      "#8800ff",
      "#00aaaa",
      "#aa00aa"
    ];
    this.container = container;
    this.app = app;
    this.callbacks = callbacks;
    this.build();
  }
  build() {
    this.container.addClass("handnotes-toolbar");
    const toggleBtn = this.container.createEl("button", {
      cls: "handnotes-tb-toggle"
    });
    (0, import_obsidian.setIcon)(toggleBtn, "chevron-left");
    toggleBtn.addEventListener("click", () => {
      this.collapsed = !this.collapsed;
      this.container.toggleClass("handnotes-tb-collapsed", this.collapsed);
      (0, import_obsidian.setIcon)(toggleBtn, this.collapsed ? "chevron-right" : "chevron-left");
    });
    const tools = [
      { type: "fountain", icon: "fountain", label: "Fountain Pen" },
      { type: "ballpoint", icon: "ballpoint", label: "Ballpoint" },
      { type: "pencil", icon: "pencil", label: "Pencil" },
      { type: "marker", icon: "marker", label: "Marker" },
      { type: "eraser", icon: "eraser", label: "Eraser" },
      { type: "selection", icon: "selection", label: "Select" },
      { type: "pan", icon: "pan", label: "Pan" }
    ];
    const btnGroup = this.container.createDiv({ cls: "handnotes-tb-buttons" });
    for (const t of tools) {
      const btn = btnGroup.createEl("button", {
        cls: "handnotes-tb-btn",
        attr: { "data-tool": t.type, "title": t.label }
      });
      btn.innerHTML = TOOL_SVGS[t.type] || "";
      btn.addEventListener("click", () => this.onToolClick(t.type));
    }
    const spacer = this.container.createDiv({ cls: "handnotes-tb-spacer" });
    const undoBtn = btnGroup.createEl("button", {
      cls: "handnotes-tb-btn",
      attr: { title: "Undo" }
    });
    (0, import_obsidian.setIcon)(undoBtn, "undo");
    undoBtn.addEventListener("click", () => this.callbacks.onUndo());
    const redoBtn = btnGroup.createEl("button", {
      cls: "handnotes-tb-btn",
      attr: { title: "Redo" }
    });
    (0, import_obsidian.setIcon)(redoBtn, "redo");
    redoBtn.addEventListener("click", () => this.callbacks.onRedo());
    const insertBtn = btnGroup.createEl("button", {
      cls: "handnotes-tb-btn",
      attr: { title: "Insert Image" }
    });
    (0, import_obsidian.setIcon)(insertBtn, "image");
    insertBtn.addEventListener("click", () => this.callbacks.onInsertImage());
    const clearBtn = btnGroup.createEl("button", {
      cls: "handnotes-tb-btn",
      attr: { title: "Clear All" }
    });
    (0, import_obsidian.setIcon)(clearBtn, "trash-2");
    clearBtn.addEventListener("click", () => {
      if (confirm("Clear all strokes?")) {
        this.callbacks.onClearAll();
      }
    });
    this.highlightActiveTool();
  }
  onToolClick(tool) {
    if (tool === this.activeTool) {
      this.togglePopup();
    } else {
      this.closePopup();
      this.activeTool = tool;
      this.highlightActiveTool();
      this.callbacks.onToolChange(tool);
    }
  }
  highlightActiveTool() {
    this.container.querySelectorAll(".handnotes-tb-btn[data-tool]").forEach((el) => {
      el.toggleClass("is-active", el.dataset.tool === this.activeTool);
    });
  }
  togglePopup() {
    if (this.popupEl && this.popupEl.isConnected) {
      this.closePopup();
    } else {
      this.openPopup();
    }
  }
  openPopup() {
    this.closePopup();
    this.popupEl = this.container.createDiv({ cls: "handnotes-tb-popup" });
    this.buildPopupContent(this.popupEl);
  }
  closePopup() {
    if (this.popupEl) {
      this.popupEl.remove();
      this.popupEl = null;
    }
  }
  buildPopupContent(el) {
    const colorSection = el.createDiv({ cls: "handnotes-popup-section" });
    colorSection.createEl("label", { text: "Color", cls: "handnotes-popup-label" });
    const colorRow = colorSection.createDiv({ cls: "handnotes-popup-color-row" });
    let hue = 0, saturation = 100, lightness = 50;
    const hueContainer = colorRow.createDiv({ cls: "handnotes-popup-hue" });
    const hueCanvas = hueContainer.createEl("canvas", { attr: { width: 200, height: 16 } });
    this.drawHueGradient(hueCanvas);
    this.drawHueCursor(hueCanvas, hue);
    const satLightContainer = colorRow.createDiv({ cls: "handnotes-popup-sat-light" });
    const slCanvas = satLightContainer.createEl("canvas", { attr: { width: 180, height: 150 } });
    this.drawSLGradient(slCanvas, hue);
    this.drawSLCursor(slCanvas, saturation, lightness);
    const previewContainer = colorRow.createDiv({ cls: "handnotes-popup-preview" });
    const preview = previewContainer.createEl("canvas", { attr: { width: 40, height: 40 } });
    this.updatePreviewColor(preview, hue, saturation, lightness);
    const setupDrag = (canvas, onMove) => {
      let dragging = false;
      const handle = (clientX, clientY) => {
        onMove(clientX, clientY);
        this.drawHueGradient(hueCanvas);
        this.drawHueCursor(hueCanvas, hue);
        this.drawSLGradient(slCanvas, hue);
        this.drawSLCursor(slCanvas, saturation, lightness);
        this.updatePreviewColor(preview, hue, saturation, lightness);
        const color = `hsl(${hue}, ${saturation}%, ${lightness}%)`;
        this.currentColor = color;
        this.callbacks.onColorChange(color);
        this.updateWidthPreview(el);
      };
      canvas.addEventListener("pointerdown", (e) => {
        dragging = true;
        canvas.setPointerCapture(e.pointerId);
        handle(e.clientX, e.clientY);
      });
      canvas.addEventListener("pointermove", (e) => {
        if (!dragging)
          return;
        handle(e.clientX, e.clientY);
      });
      canvas.addEventListener("pointerup", () => {
        dragging = false;
      });
      canvas.addEventListener("pointercancel", () => {
        dragging = false;
      });
    };
    setupDrag(hueCanvas, (clientX) => {
      const r = hueCanvas.getBoundingClientRect();
      hue = Math.max(0, Math.min(360, (clientX - r.left) / r.width * 360));
    });
    setupDrag(slCanvas, (clientX, clientY) => {
      const r = slCanvas.getBoundingClientRect();
      saturation = Math.max(0, Math.min(100, (clientX - r.left) / r.width * 100));
      lightness = Math.max(0, Math.min(100, (1 - (clientY - r.top) / r.height) * 100));
    });
    const recentSection = el.createDiv({ cls: "handnotes-popup-section" });
    recentSection.createEl("label", { text: "Recent", cls: "handnotes-popup-label" });
    const swatchRow = recentSection.createDiv({ cls: "handnotes-popup-swatches" });
    for (const c of this.recentColors) {
      const swatch = swatchRow.createEl("button", {
        cls: "handnotes-popup-swatch",
        attr: { style: `background-color: ${c}` }
      });
      swatch.addEventListener("click", () => {
        this.currentColor = c;
        this.callbacks.onColorChange(c);
        this.closePopup();
      });
    }
    const widthSection = el.createDiv({ cls: "handnotes-popup-section" });
    widthSection.createEl("label", { text: `Width: ${this.currentWidth}`, cls: "handnotes-popup-label" });
    const widthSlider = widthSection.createEl("input", {
      cls: "handnotes-popup-slider",
      attr: { type: "range", min: "0.5", max: "20", step: "0.5", value: String(this.currentWidth) }
    });
    widthSlider.addEventListener("input", () => {
      const val = parseFloat(widthSlider.value);
      this.currentWidth = val;
      widthSection.querySelector("label").textContent = `Width: ${val}`;
      this.callbacks.onWidthChange(val);
      this.updateWidthPreview(el);
    });
    if (this.activeTool === "marker") {
      const opacitySection = el.createDiv({ cls: "handnotes-popup-section" });
      opacitySection.createEl("label", { text: `Opacity: ${Math.round(this.currentOpacity * 100)}%`, cls: "handnotes-popup-label" });
      const opacitySlider = opacitySection.createEl("input", {
        cls: "handnotes-popup-slider",
        attr: { type: "range", min: "0", max: "1", step: "0.05", value: String(this.currentOpacity) }
      });
      opacitySlider.addEventListener("input", () => {
        const val = parseFloat(opacitySlider.value);
        this.currentOpacity = val;
        opacitySection.querySelector("label").textContent = `Opacity: ${Math.round(val * 100)}%`;
        this.callbacks.onOpacityChange(val);
      });
    }
  }
  updateWidthPreview(el) {
    const cv = el.querySelector(".handnotes-popup-section canvas:not(.handnotes-popup-preview canvas):not(.handnotes-popup-hue canvas):not(.handnotes-popup-sat-light canvas)");
    if (cv)
      this.drawWidthPreview(cv, this.currentColor, this.currentWidth);
  }
  drawHueGradient(canvas) {
    const ctx = canvas.getContext("2d");
    const grad = ctx.createLinearGradient(0, 0, canvas.width, 0);
    for (let i = 0; i <= 360; i += 30) {
      grad.addColorStop(i / 360, `hsl(${i}, 100%, 50%)`);
    }
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
  }
  drawHueCursor(canvas, hue) {
    const ctx = canvas.getContext("2d");
    const x = hue / 360 * canvas.width;
    ctx.beginPath();
    ctx.moveTo(x, 0);
    ctx.lineTo(x - 5, 5);
    ctx.lineTo(x + 5, 5);
    ctx.closePath();
    ctx.fillStyle = "#000";
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(x, canvas.height);
    ctx.lineTo(x - 5, canvas.height - 5);
    ctx.lineTo(x + 5, canvas.height - 5);
    ctx.closePath();
    ctx.fill();
  }
  drawSLGradient(canvas, hue) {
    const ctx = canvas.getContext("2d");
    const w = canvas.width, h = canvas.height;
    const imgData = ctx.createImageData(w, h);
    const d = imgData.data;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const s = x / w * 100;
        const l = (1 - y / h) * 100;
        const rgb = this.hslToRgb(hue / 360, s / 100, l / 100);
        const i = (y * w + x) * 4;
        d[i] = rgb[0];
        d[i + 1] = rgb[1];
        d[i + 2] = rgb[2];
        d[i + 3] = 255;
      }
    }
    ctx.putImageData(imgData, 0, 0);
  }
  drawSLCursor(canvas, saturation, lightness) {
    const ctx = canvas.getContext("2d");
    const cx = saturation / 100 * canvas.width;
    const cy = (1 - lightness / 100) * canvas.height;
    const invL = lightness > 50 ? 0 : 255;
    ctx.beginPath();
    ctx.arc(cx, cy, 5, 0, Math.PI * 2);
    ctx.strokeStyle = `rgb(${invL},${invL},${invL})`;
    ctx.lineWidth = 2;
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(cx, cy, 4, 0, Math.PI * 2);
    ctx.strokeStyle = `rgb(${255 - invL},${255 - invL},${255 - invL})`;
    ctx.lineWidth = 1.5;
    ctx.stroke();
  }
  hslToRgb(h, s, l) {
    let r, g, b;
    if (s === 0) {
      r = g = b = l;
    } else {
      const hue2rgb = (p2, q2, t) => {
        if (t < 0)
          t += 1;
        if (t > 1)
          t -= 1;
        if (t < 1 / 6)
          return p2 + (q2 - p2) * 6 * t;
        if (t < 1 / 2)
          return q2;
        if (t < 2 / 3)
          return p2 + (q2 - p2) * (2 / 3 - t) * 6;
        return p2;
      };
      const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
      const p = 2 * l - q;
      r = hue2rgb(p, q, h + 1 / 3);
      g = hue2rgb(p, q, h);
      b = hue2rgb(p, q, h - 1 / 3);
    }
    return [Math.round(r * 255), Math.round(g * 255), Math.round(b * 255)];
  }
  updateColorDisplay(el, h, s, l) {
    const color = `hsl(${h}, ${s}%, ${l}%)`;
    this.currentColor = color;
    this.callbacks.onColorChange(color);
    const preview = el.querySelector(".handnotes-popup-preview canvas");
    if (preview)
      this.updatePreviewColor(preview, h, s, l);
    this.updateWidthPreview(el);
  }
  updatePreviewColor(canvas, h, s, l) {
    const ctx = canvas.getContext("2d");
    ctx.fillStyle = `hsl(${h}, ${s}%, ${l}%)`;
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.strokeStyle = "#999";
    ctx.lineWidth = 1;
    ctx.strokeRect(0, 0, canvas.width, canvas.height);
  }
  drawWidthPreview(canvas, color, width) {
    const ctx = canvas.getContext("2d");
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.strokeStyle = color;
    ctx.lineWidth = width;
    ctx.lineCap = "round";
    ctx.beginPath();
    ctx.moveTo(10, canvas.height / 2);
    ctx.lineTo(canvas.width - 10, canvas.height / 2);
    ctx.stroke();
  }
  setTool(tool) {
    this.activeTool = tool;
    this.highlightActiveTool();
    this.closePopup();
  }
  setColor(color) {
    this.currentColor = color;
  }
  setWidth(width) {
    this.currentWidth = width;
  }
  setOpacity(opacity) {
    this.currentOpacity = opacity;
  }
  setRecentColors(colors) {
    if (colors.length > 0)
      this.recentColors = colors;
  }
};

// src/ui/LayoutPicker.ts
var LayoutPicker = class {
  constructor(container, onChange) {
    this.currentLayout = "blank";
    this.container = container;
    this.onLayoutChange = onChange;
    this.build();
  }
  build() {
    this.container.addClass("handnotes-layout-picker");
    const layouts = [
      { value: "blank", label: "Blank", icon: "\u229E" },
      { value: "ruled-narrow", label: "Ruled (narrow)", icon: "\u2261" },
      { value: "ruled-wide", label: "Ruled (wide)", icon: "\u2630" },
      { value: "grid-small", label: "Grid (small)", icon: "\u25A6" },
      { value: "grid-large", label: "Grid (large)", icon: "\u25A4" },
      { value: "dot", label: "Dot grid", icon: "\u22EF" },
      { value: "isometric", label: "Isometric", icon: "\u2B21" }
    ];
    const select = this.container.createEl("select", {
      cls: "handnotes-layout-select"
    });
    for (const layout of layouts) {
      const option = select.createEl("option", {
        value: layout.value,
        text: `${layout.icon} ${layout.label}`
      });
      if (layout.value === this.currentLayout) {
        option.selected = true;
      }
    }
    select.addEventListener("change", () => {
      this.currentLayout = select.value;
      this.onLayoutChange(this.currentLayout);
    });
  }
  setLayout(layout) {
    this.currentLayout = layout;
    const select = this.container.querySelector("select");
    if (select) {
      select.value = layout;
    }
  }
  getLayout() {
    return this.currentLayout;
  }
};

// src/assets/AssetManager.ts
var import_obsidian2 = require("obsidian");
var AssetManager = class {
  constructor(app) {
    this.app = app;
  }
  getAssetFolderPath(notePath, folderName) {
    const noteDir = notePath.substring(0, notePath.lastIndexOf("/") + 1) || "";
    return `${noteDir}${folderName}`;
  }
  async ensureAssetFolder(notePath, folderName) {
    const folderPath = this.getAssetFolderPath(notePath, folderName);
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await this.app.vault.createFolder(folderPath);
    }
    return folderPath;
  }
  async importImage(notePath, folderName, fileName, data) {
    try {
      const folder = await this.ensureAssetFolder(notePath, folderName);
      const uniqueName = `${Date.now()}_${fileName.replace(/[^a-zA-Z0-9._-]/g, "_")}`;
      const filePath = `${folder}/${uniqueName}`;
      const existing = this.app.vault.getAbstractFileByPath(filePath);
      if (!existing) {
        await this.app.vault.createBinary(filePath, data);
      }
      return {
        id: `asset_${Date.now()}`,
        type: "image",
        path: filePath,
        x: 0,
        y: 0,
        width: 400,
        height: 300
      };
    } catch (err) {
      new import_obsidian2.Notice(`Failed to import image: ${err}`);
      return null;
    }
  }
  async importPdf(notePath, folderName, fileName, data) {
    try {
      const folder = await this.ensureAssetFolder(notePath, folderName);
      const uniqueName = `${Date.now()}_${fileName.replace(/[^a-zA-Z0-9._-]/g, "_")}`;
      const filePath = `${folder}/${uniqueName}`;
      const existing = this.app.vault.getAbstractFileByPath(filePath);
      if (!existing) {
        await this.app.vault.createBinary(filePath, data);
      }
      const asset = {
        id: `asset_${Date.now()}`,
        type: "pdf",
        path: filePath,
        x: 0,
        y: 0,
        width: 600,
        height: 800
      };
      return [asset];
    } catch (err) {
      new import_obsidian2.Notice(`Failed to import PDF: ${err}`);
      return [];
    }
  }
  async readFileAsArrayBuffer(filePath) {
    try {
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file instanceof import_obsidian2.TFile) {
        return await this.app.vault.readBinary(file);
      }
      return null;
    } catch {
      return null;
    }
  }
  async getAssetUrl(assetPath) {
    try {
      const file = this.app.vault.getAbstractFileByPath(assetPath);
      if (file instanceof import_obsidian2.TFile) {
        const resourcePath = this.app.vault.getResourcePath(file);
        return resourcePath;
      }
      return null;
    } catch {
      return null;
    }
  }
};

// src/HandnotesView.ts
var VIEW_TYPE = "handnotes-view";
var HandnotesView = class extends import_obsidian3.ItemView {
  constructor(leaf, app, settings) {
    super(leaf);
    this.canvas = null;
    this.toolbar = null;
    this.layoutPicker = null;
    this.filePath = "";
    this.saveTimer = null;
    this.resizeObserver = null;
    this.assetManager = new AssetManager(app);
    this.settings = settings;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return this.filePath ? this.filePath.split("/").pop() || "Handnote" : "Handnote";
  }
  getIcon() {
    return "pen";
  }
  async onOpen() {
    const contentEl = this.contentEl;
    contentEl.empty();
    contentEl.addClass("handnotes-view");
    this.topBarEl = contentEl.createDiv({ cls: "handnotes-topbar" });
    this.canvasContainer = contentEl.createDiv({ cls: "handnotes-canvas-container" });
    this.toolbarEl = contentEl.createDiv({ cls: "handnotes-toolbar-container" });
    this.layoutPicker = new LayoutPicker(this.topBarEl, (layout) => {
      if (this.canvas) {
        this.canvas.setLayout(layout);
        this.scheduleSave();
      }
    });
    const callbacks = {
      onToolChange: (tool) => this.canvas?.setTool(tool),
      onColorChange: (color) => this.canvas?.setColor(color),
      onWidthChange: (width) => this.canvas?.setWidth(width),
      onOpacityChange: (opacity) => this.canvas?.setOpacity(opacity),
      onUndo: () => this.canvas?.undo(),
      onRedo: () => this.canvas?.redo(),
      onInsertImage: () => this.insertImage(),
      onClearAll: () => {
        this.canvas?.clearAll();
        this.scheduleSave();
      }
    };
    this.toolbar = new Toolbar(this.toolbarEl, this.app, callbacks);
    this.canvas = new HandwritingCanvas(this.canvasContainer);
    this.canvas.onSaveNeeded = () => this.scheduleSave();
    this.canvas.onStrokeAdded = () => {
    };
    this.applySettings();
    if (this.filePath) {
      await this.loadFile(this.filePath);
    }
    this.resizeObserver = new ResizeObserver(() => {
      this.canvas?.onResize();
    });
    this.resizeObserver.observe(this.canvasContainer);
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.canvas?.onResize();
      })
    );
    if (import_obsidian3.Platform.isIosApp || import_obsidian3.Platform.isAndroidApp) {
      this.canvas?.setPalmRejection(true);
    }
  }
  async onClose() {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    await this.saveFile();
    this.resizeObserver?.disconnect();
    this.canvas?.destroy();
  }
  async loadFile(path) {
    this.filePath = path;
    if (!this.canvas)
      return;
    try {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian3.TFile)) {
        new import_obsidian3.Notice("File not found");
        return;
      }
      const content = await this.app.vault.read(file);
      const data = JSON.parse(content);
      this.migrateFile(data);
      this.canvas.fromHandnotesFile(data);
      this.layoutPicker?.setLayout(data.state?.background || this.settings.defaultLayout);
    } catch (err) {
      new import_obsidian3.Notice(`Failed to load handnote: ${err}`);
    }
  }
  migrateFile(file) {
    if (!file.version || file.version < 1) {
      file.version = 1;
    }
    if (!file.state) {
      file.state = {
        zoom: 1,
        offsetX: 0,
        offsetY: 0,
        background: this.settings.defaultLayout
      };
    }
    if (!file.strokes)
      file.strokes = [];
    if (!file.assets)
      file.assets = [];
  }
  async saveFile() {
    if (!this.canvas || !this.filePath)
      return;
    try {
      const data = this.canvas.toHandnotesFile();
      const json = JSON.stringify(data, null, 2);
      await this.app.vault.adapter.write(this.filePath, json);
    } catch (err) {
      new import_obsidian3.Notice(`Failed to save handnote: ${err}`);
    }
  }
  scheduleSave() {
    if (this.saveTimer !== null) {
      clearTimeout(this.saveTimer);
    }
    const interval = (this.settings.autoSaveInterval || 5) * 1e3;
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      this.saveFile();
    }, interval);
  }
  applySettings() {
    if (!this.canvas)
      return;
    this.canvas.setSmoothing(this.settings.strokeSmoothing);
    this.canvas.setPalmRejection(this.settings.palmRejection);
    this.canvas.maxUndo = this.settings.maxUndoHistory;
    this.canvas.setDarkMode(this.settings.darkModeCanvasBg);
    this.canvas.setPressureCurve(this.settings.pressureCurve);
    for (const [tool, enabled] of Object.entries(this.settings.toolPressureEnabled)) {
      this.canvas.setToolPressureEnabled(tool, enabled);
    }
    this.canvas.setTool(this.settings.defaultTool);
    this.toolbar?.setTool(this.settings.defaultTool);
    this.layoutPicker?.setLayout(this.settings.defaultLayout);
  }
  updateSettings(settings) {
    this.settings = settings;
    this.applySettings();
  }
  async insertImage() {
    if (!this.canvas || !this.filePath)
      return;
    const input = document.createElement("input");
    input.type = "file";
    input.accept = "image/png,image/jpeg,image/svg+xml";
    input.onchange = async () => {
      const file = input.files?.[0];
      if (!file)
        return;
      const buffer = await file.arrayBuffer();
      const asset = await this.assetManager.importImage(
        this.filePath,
        this.settings.assetFolderName,
        file.name,
        buffer
      );
      if (asset) {
        this.canvas.assets.push(asset);
        this.canvas.loadAssets(this.canvas.assets);
        this.scheduleSave();
      }
    };
    input.click();
  }
};

// src/HandnotesEmbed.ts
var import_obsidian4 = require("obsidian");
function registerHandnotesEmbed(plugin, app, getSettings) {
  plugin.registerMarkdownCodeBlockProcessor("handnotes", async (source, el, ctx) => {
    const filePath = source.trim();
    if (!filePath) {
      el.createEl("div", { text: "[Handnotes: no file path]", cls: "handnotes-embed-error" });
      return;
    }
    let resolvedPath = filePath;
    const noteFile = ctx.sourcePath;
    if (!filePath.startsWith("/")) {
      const noteDir = noteFile.substring(0, noteFile.lastIndexOf("/") + 1) || "";
      resolvedPath = noteDir + filePath;
    }
    const abstractFile = app.vault.getAbstractFileByPath(resolvedPath);
    if (!abstractFile || !(abstractFile instanceof import_obsidian4.TFile)) {
      el.createEl("div", {
        text: `[Handnotes: file not found \u2014 ${resolvedPath}]`,
        cls: "handnotes-embed-error"
      });
      return;
    }
    el.addClass("handnotes-embed");
    const container = el.createDiv({ cls: "handnotes-embed-canvas" });
    try {
      const content = await app.vault.read(abstractFile);
      const data = JSON.parse(content);
      const canvas = new HandwritingCanvas(container);
      canvas.fromHandnotesFile(data);
      canvas.setDarkMode(getSettings().darkModeCanvasBg);
      canvas.setSmoothing(getSettings().strokeSmoothing);
      canvas.onSaveNeeded = null;
      const resizeObserver = new ResizeObserver(() => {
        canvas.onResize();
      });
      resizeObserver.observe(container);
      plugin.register(() => resizeObserver.disconnect());
      plugin.register(() => canvas.destroy());
      el.style.minHeight = "300px";
      const updateHeight = () => {
        const rect = container.getBoundingClientRect();
        if (rect.height < 300) {
          el.style.height = "300px";
        }
      };
      updateHeight();
    } catch (err) {
      el.createEl("div", {
        text: `[Handnotes: error loading \u2014 ${err}]`,
        cls: "handnotes-embed-error"
      });
    }
  });
}

// src/settings/SettingsTab.ts
var import_obsidian5 = require("obsidian");

// src/settings/PressureCurveEditor.ts
var PressureCurveEditor = class {
  constructor(container, config, onChange) {
    this.draggingIndex = null;
    this.testPoints = [];
    this.isDrawingTest = false;
    this.container = container;
    this.config = JSON.parse(JSON.stringify(config));
    this.onChange = onChange;
    this.graphCanvas = document.createElement("canvas");
    this.testCanvas = document.createElement("canvas");
    this.graphCtx = this.graphCanvas.getContext("2d");
    this.testCtx = this.testCanvas.getContext("2d");
    this.build();
    this.renderGraph();
  }
  build() {
    const wrapper = this.container.createDiv({ cls: "handnotes-curve-editor" });
    const graphSection = wrapper.createDiv({ cls: "handnotes-curve-graph-section" });
    graphSection.createEl("h3", { text: "Pressure Curve" });
    this.graphCanvas.width = 300;
    this.graphCanvas.height = 300;
    this.graphCanvas.addClass("handnotes-curve-canvas");
    graphSection.appendChild(this.graphCanvas);
    const btnRow = graphSection.createDiv({ cls: "handnotes-curve-buttons" });
    const deleteBtn = btnRow.createEl("button", { text: "Delete Handle", cls: "mod-warning" });
    deleteBtn.addEventListener("click", () => this.deleteSelectedHandle());
    const resetBtn = btnRow.createEl("button", { text: "Reset", cls: "mod-cta" });
    resetBtn.addEventListener("click", () => this.resetCurve());
    const testSection = wrapper.createDiv({ cls: "handnotes-curve-test-section" });
    testSection.createEl("h3", { text: "Test Area" });
    this.testCanvas.width = 200;
    this.testCanvas.height = 200;
    this.testCanvas.addClass("handnotes-curve-test-canvas");
    testSection.appendChild(this.testCanvas);
    this.setupGraphEvents();
    this.setupTestEvents();
  }
  setupGraphEvents() {
    this.graphCanvas.addEventListener("mousedown", (e) => {
      const rect = this.graphCanvas.getBoundingClientRect();
      const mx = (e.clientX - rect.left) / this.graphCanvas.width;
      const my = 1 - (e.clientY - rect.top) / this.graphCanvas.height;
      for (let i = 0; i < this.config.points.length; i++) {
        const p = this.config.points[i];
        const px = p.x;
        const py = p.y;
        const dist = Math.sqrt((mx - px) ** 2 + (my - py) ** 2);
        if (dist < 0.04) {
          this.draggingIndex = i;
          return;
        }
      }
      if (mx > 0.05 && mx < 0.95 && my > 0.05 && my < 0.95) {
        const insertAt = this.config.points.findIndex((p) => p.x > mx);
        if (insertAt === -1) {
          this.config.points.push({ x: mx, y: my });
          this.draggingIndex = this.config.points.length - 1;
        } else {
          this.config.points.splice(insertAt, 0, { x: mx, y: my });
          this.draggingIndex = insertAt;
        }
        this.renderGraph();
        this.emitChange();
      }
    });
    window.addEventListener("mousemove", (e) => {
      if (this.draggingIndex === null)
        return;
      const rect = this.graphCanvas.getBoundingClientRect();
      let mx = (e.clientX - rect.left) / this.graphCanvas.width;
      let my = 1 - (e.clientY - rect.top) / this.graphCanvas.height;
      mx = Math.max(0, Math.min(1, mx));
      my = Math.max(0, Math.min(1, my));
      const idx = this.draggingIndex;
      if (idx <= 0 || idx >= this.config.points.length - 1)
        return;
      const prev = this.config.points[idx - 1];
      const next = this.config.points[idx + 1];
      if (mx <= prev.x || mx >= next.x)
        return;
      this.config.points[idx] = { x: mx, y: my };
      this.renderGraph();
      this.emitChange();
    });
    window.addEventListener("mouseup", () => {
      this.draggingIndex = null;
    });
  }
  setupTestEvents() {
    this.testCanvas.addEventListener("pointerdown", (e) => {
      this.isDrawingTest = true;
      this.testPoints = [];
      const rect = this.testCanvas.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      this.testPoints.push({ x, y });
    });
    this.testCanvas.addEventListener("pointermove", (e) => {
      if (!this.isDrawingTest)
        return;
      const rect = this.testCanvas.getBoundingClientRect();
      const x = e.clientX - rect.left;
      const y = e.clientY - rect.top;
      this.testPoints.push({ x, y });
      this.renderTest();
    });
    this.testCanvas.addEventListener("pointerup", () => {
      this.isDrawingTest = false;
    });
    this.testCanvas.addEventListener("pointerleave", () => {
      this.isDrawingTest = false;
    });
  }
  renderGraph() {
    const ctx = this.graphCtx;
    const w = this.graphCanvas.width;
    const h = this.graphCanvas.height;
    ctx.fillStyle = "#1e1e1e";
    ctx.fillRect(0, 0, w, h);
    const pad = 20;
    const gw = w - pad * 2;
    const gh = h - pad * 2;
    ctx.strokeStyle = "#444";
    ctx.lineWidth = 0.5;
    for (let i = 0; i <= 4; i++) {
      const x = pad + gw * i / 4;
      const y = pad + gh * i / 4;
      ctx.beginPath();
      ctx.moveTo(x, pad);
      ctx.lineTo(x, pad + gh);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(pad, y);
      ctx.lineTo(pad + gw, y);
      ctx.stroke();
    }
    ctx.strokeStyle = "#555";
    ctx.lineWidth = 0.5;
    ctx.strokeRect(pad, pad, gw, gh);
    ctx.fillStyle = "#888";
    ctx.font = "10px monospace";
    ctx.textAlign = "center";
    ctx.fillText("0", pad, pad + gh + 14);
    ctx.fillText("0.5", pad + gw / 2, pad + gh + 14);
    ctx.fillText("1", pad + gw, pad + gh + 14);
    ctx.textAlign = "right";
    ctx.fillText("0", pad - 4, pad + gh + 4);
    ctx.fillText("0.5", pad - 4, pad + gh / 2 + 4);
    ctx.fillText("1", pad - 4, pad + 4);
    if (this.config.points.length >= 2) {
      ctx.beginPath();
      ctx.strokeStyle = "#3b82f6";
      ctx.lineWidth = 2;
      const steps = 100;
      const sorted = [...this.config.points].sort((a, b) => a.x - b.x);
      const interpolator = monotoneCubicSpline(sorted);
      for (let i = 0; i <= steps; i++) {
        const t = i / steps;
        const y = interpolator(t);
        const px = pad + t * gw;
        const py = pad + (1 - y) * gh;
        if (i === 0)
          ctx.moveTo(px, py);
        else
          ctx.lineTo(px, py);
      }
      ctx.stroke();
      for (let i = 0; i < sorted.length; i++) {
        const p = sorted[i];
        const cx = pad + p.x * gw;
        const cy = pad + (1 - p.y) * gh;
        ctx.fillStyle = i === 0 || i === sorted.length - 1 ? "#888" : "#3b82f6";
        ctx.beginPath();
        ctx.arc(cx, cy, i === this.draggingIndex ? 7 : 5, 0, Math.PI * 2);
        ctx.fill();
        if (i > 0 && i < sorted.length - 1) {
          ctx.strokeStyle = "rgba(255,255,255,0.3)";
          ctx.lineWidth = 1;
          ctx.strokeRect(cx - 6, cy - 6, 12, 12);
        }
      }
    }
    ctx.fillStyle = "#aaa";
    ctx.font = "10px monospace";
    ctx.textAlign = "left";
    ctx.fillText("Raw pressure \u2192", 5, 12);
    ctx.save();
    ctx.translate(8, h / 2);
    ctx.rotate(-Math.PI / 2);
    ctx.fillText("Output pressure \u2190", 0, 0);
    ctx.restore();
  }
  renderTest() {
    const ctx = this.testCtx;
    const w = this.testCanvas.width;
    const h = this.testCanvas.height;
    ctx.fillStyle = "#fff";
    ctx.fillRect(0, 0, w, h);
    if (this.testPoints.length < 2)
      return;
    ctx.strokeStyle = "#000";
    ctx.lineWidth = 2;
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    ctx.beginPath();
    const interpolator = this.config.points.length >= 2 ? monotoneCubicSpline(this.config.points.sort((a, b) => a.x - b.x)) : (t) => t;
    const pressureFn = (raw) => {
      return interpolator(Math.max(0, Math.min(1, raw)));
    };
    ctx.moveTo(this.testPoints[0].x, this.testPoints[0].y);
    for (let i = 1; i < this.testPoints.length; i++) {
      const dx = this.testPoints[i].x - this.testPoints[i - 1].x;
      const dy = this.testPoints[i].y - this.testPoints[i - 1].y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      const rawPressure = Math.min(1, dist / 10);
      const pressure = pressureFn(rawPressure);
      const lineW = 1 + pressure * 4;
      ctx.lineWidth = lineW;
      ctx.lineTo(this.testPoints[i].x, this.testPoints[i].y);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(this.testPoints[i].x, this.testPoints[i].y);
    }
  }
  deleteSelectedHandle() {
    if (this.config.points.length <= 2)
      return;
    if (this.draggingIndex !== null && this.draggingIndex > 0 && this.draggingIndex < this.config.points.length - 1) {
      this.config.points.splice(this.draggingIndex, 1);
      this.draggingIndex = null;
      this.renderGraph();
      this.emitChange();
    }
  }
  resetCurve() {
    this.config.points = [
      { x: 0, y: 0 },
      { x: 0.3, y: 0.2 },
      { x: 0.7, y: 0.8 },
      { x: 1, y: 1 }
    ];
    this.draggingIndex = null;
    this.renderGraph();
    this.emitChange();
  }
  emitChange() {
    this.onChange(JSON.parse(JSON.stringify(this.config)));
  }
  getConfig() {
    return JSON.parse(JSON.stringify(this.config));
  }
  setConfig(config) {
    this.config = JSON.parse(JSON.stringify(config));
    this.renderGraph();
  }
};

// src/settings/SettingsTab.ts
var HandnotesSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin, settings, onSettingsChange) {
    super(app, plugin);
    this.plugin = plugin;
    this.settings = settings;
    this.onSettingsChange = onSettingsChange;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Handnotes Settings" });
    this.addApplePencilSection(containerEl);
    this.addSyncSection(containerEl);
    this.addAppearanceSection(containerEl);
    this.addPerformanceSection(containerEl);
  }
  addApplePencilSection(containerEl) {
    containerEl.createEl("h3", { text: "Apple Pencil & Stylus" });
    const curveDesc = containerEl.createDiv({ cls: "setting-item-description" });
    curveDesc.setText(
      "Drag the blue handles to adjust the pressure response curve. Add new handles by clicking on the graph."
    );
    const curveContainer = containerEl.createDiv({ cls: "handnotes-settings-curve" });
    const curveEditor = new PressureCurveEditor(
      curveContainer,
      this.settings.pressureCurve,
      (config) => {
        this.settings.pressureCurve = config;
        this.saveSettings();
      }
    );
    new import_obsidian5.Setting(containerEl).setName("Palm rejection").setDesc("Only process pen/stylus events on the drawing canvas").addToggle(
      (toggle) => toggle.setValue(this.settings.palmRejection).onChange(async (value) => {
        this.settings.palmRejection = value;
        await this.saveSettings();
      })
    );
    containerEl.createEl("h4", { text: "Per-tool pressure sensitivity" });
    const tools = [
      "fountain",
      "ballpoint",
      "pencil",
      "marker"
    ];
    for (const tool of tools) {
      const label = tool.charAt(0).toUpperCase() + tool.slice(1);
      new import_obsidian5.Setting(containerEl).setName(label).addToggle(
        (toggle) => toggle.setValue(this.settings.toolPressureEnabled[tool] ?? true).onChange(async (value) => {
          this.settings.toolPressureEnabled[tool] = value;
          await this.saveSettings();
        })
      );
    }
  }
  addSyncSection(containerEl) {
    containerEl.createEl("h3", { text: "Sync & Storage" });
    new import_obsidian5.Setting(containerEl).setName("Asset folder name").setDesc("Subfolder name for storing embedded images and PDFs beside your notes").addText(
      (text) => text.setPlaceholder("_handnotes_assets").setValue(this.settings.assetFolderName).onChange(async (value) => {
        this.settings.assetFolderName = value || "_handnotes_assets";
        await this.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Auto-save interval").setDesc("How often to auto-save your drawing (in seconds)").addSlider(
      (slider) => slider.setLimits(1, 30, 1).setValue(this.settings.autoSaveInterval).setDynamicTooltip().onChange(async (value) => {
        this.settings.autoSaveInterval = value;
        await this.saveSettings();
      })
    );
  }
  addAppearanceSection(containerEl) {
    containerEl.createEl("h3", { text: "Appearance" });
    new import_obsidian5.Setting(containerEl).setName("Default tool on open").setDesc("Which drawing tool is selected when opening a handnote").addDropdown((dropdown) => {
      const tools = [
        { value: "fountain", label: "Fountain Pen" },
        { value: "ballpoint", label: "Ballpoint" },
        { value: "pencil", label: "Pencil" },
        { value: "marker", label: "Marker" },
        { value: "eraser", label: "Eraser" },
        { value: "selection", label: "Selection" },
        { value: "pan", label: "Pan" }
      ];
      for (const t of tools) {
        dropdown.addOption(t.value, t.label);
      }
      dropdown.setValue(this.settings.defaultTool);
      dropdown.onChange(async (value) => {
        this.settings.defaultTool = value;
        await this.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Default page layout").setDesc("Background pattern for new handnotes").addDropdown((dropdown) => {
      const layouts = [
        { value: "blank", label: "Blank" },
        { value: "ruled-narrow", label: "Ruled (narrow)" },
        { value: "ruled-wide", label: "Ruled (wide)" },
        { value: "grid-small", label: "Grid (small)" },
        { value: "grid-large", label: "Grid (large)" },
        { value: "dot", label: "Dot grid" },
        { value: "isometric", label: "Isometric" }
      ];
      for (const l of layouts) {
        dropdown.addOption(l.value, l.label);
      }
      dropdown.setValue(this.settings.defaultLayout);
      dropdown.onChange(async (value) => {
        this.settings.defaultLayout = value;
        await this.saveSettings();
      });
    });
    new import_obsidian5.Setting(containerEl).setName("Dark mode canvas background").setDesc("Use dark background for the drawing canvas").addToggle(
      (toggle) => toggle.setValue(this.settings.darkModeCanvasBg).onChange(async (value) => {
        this.settings.darkModeCanvasBg = value;
        await this.saveSettings();
      })
    );
  }
  addPerformanceSection(containerEl) {
    containerEl.createEl("h3", { text: "Performance" });
    new import_obsidian5.Setting(containerEl).setName("Stroke smoothing").setDesc("Amount of rolling-average smoothing applied to raw pointer input (0 = none, 100 = maximum)").addSlider(
      (slider) => slider.setLimits(0, 100, 1).setValue(this.settings.strokeSmoothing).setDynamicTooltip().onChange(async (value) => {
        this.settings.strokeSmoothing = value;
        await this.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Max undo history").setDesc("Maximum number of undo steps to keep in memory").addText(
      (text) => text.setValue(String(this.settings.maxUndoHistory)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num > 0) {
          this.settings.maxUndoHistory = num;
          await this.saveSettings();
        }
      })
    );
  }
  async saveSettings() {
    await this.plugin.saveData(this.settings);
    this.onSettingsChange(this.settings);
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  pressureCurve: {
    points: [{ x: 0, y: 0 }, { x: 0.3, y: 0.2 }, { x: 0.7, y: 0.8 }, { x: 1, y: 1 }],
    clamp: true
  },
  palmRejection: true,
  toolPressureEnabled: {
    fountain: true,
    ballpoint: true,
    pencil: true,
    marker: false,
    eraser: false,
    selection: false,
    pan: false
  },
  assetFolderName: "_handnotes_assets",
  autoSaveInterval: 5,
  defaultTool: "fountain",
  defaultLayout: "blank",
  darkModeCanvasBg: false,
  strokeSmoothing: 50,
  maxUndoHistory: 50
};

// src/main.ts
var HANDNOTES_ICON = `
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path d="M20 80 L35 25 L50 45 L65 20 L80 75" stroke="currentColor" stroke-width="6" fill="none" stroke-linecap="round" stroke-linejoin="round"/>
  <circle cx="35" cy="25" r="4" fill="currentColor"/>
  <circle cx="65" cy="20" r="4" fill="currentColor"/>
</svg>
`;
var HandnotesPlugin = class extends import_obsidian6.Plugin {
  constructor() {
    super(...arguments);
    this.pluginSettings = DEFAULT_SETTINGS;
    this.viewInstances = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    (0, import_obsidian6.addIcon)("handnotes-pen", HANDNOTES_ICON);
    this.registerView(
      VIEW_TYPE,
      (leaf) => new HandnotesView(leaf, this.app, this.pluginSettings)
    );
    registerHandnotesEmbed(this, this.app, () => this.pluginSettings);
    this.addSettingTab(
      new HandnotesSettingTab(this.app, this, this.pluginSettings, (newSettings) => {
        this.pluginSettings = newSettings;
        this.updateAllViews();
      })
    );
    this.addCommand({
      id: "open-handnotes-file",
      name: "Open .hn file",
      callback: () => this.openHandnotesFile()
    });
    this.addCommand({
      id: "new-handnote",
      name: "Create new handnote",
      callback: () => this.createNewHandnote()
    });
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.onLayoutChange();
      })
    );
    if (import_obsidian6.Platform.isIosApp || import_obsidian6.Platform.isAndroidApp) {
      this.registerDomEvent(document, "touchstart", (e) => {
      }, { passive: true });
    }
    this.addRibbonIcon("handnotes-pen", "New Handnote", () => {
      this.createNewHandnote();
    });
    this.registerExtensions(["hn"], VIEW_TYPE);
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async loadSettings() {
    const data = await this.loadData();
    this.pluginSettings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async savePluginSettings() {
    await this.saveData(this.pluginSettings);
  }
  updateAllViews() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof HandnotesView) {
        view.updateSettings(this.pluginSettings);
      }
    });
  }
  onLayoutChange() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE).forEach((leaf) => {
      const view = leaf.view;
      if (view instanceof HandnotesView) {
        view.onResize();
      }
    });
  }
  async openHandnotesFile() {
    const files = this.app.vault.getFiles().filter((f) => f.extension === "hn");
    if (files.length === 0) {
      new import_obsidian6.Notice("No .hn files found in vault");
      return;
    }
    const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE)[0] || this.app.workspace.getRightLeaf(false);
    if (!leaf) {
      new import_obsidian6.Notice("Cannot open leaf");
      return;
    }
    await leaf.setViewState({
      type: VIEW_TYPE,
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
  }
  async createNewHandnote() {
    const folder = this.app.vault.getRoot();
    const baseName = "Untitled";
    let fileName = `${baseName}.hn`;
    let counter = 1;
    while (await this.app.vault.adapter.exists(fileName)) {
      fileName = `${baseName} ${counter}.hn`;
      counter++;
    }
    const defaultFile = {
      version: 1,
      strokes: [],
      assets: [],
      state: {
        zoom: 1,
        offsetX: 0,
        offsetY: 0,
        background: this.pluginSettings.defaultLayout
      }
    };
    await this.app.vault.create(fileName, JSON.stringify(defaultFile, null, 2));
    const leaf = this.app.workspace.getLeaf(true);
    await leaf.setViewState({
      type: VIEW_TYPE,
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
    const view = leaf.view;
    if (view instanceof HandnotesView) {
      await view.loadFile(fileName);
    }
    new import_obsidian6.Notice(`Created ${fileName}`);
  }
};
